kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: openttd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openttd
    spec:
      containers:
      - name: openttd
        image: bateau/openttd
        imagePullPolicy: Always
        ports:
        - containerPort: 3979
        env:
          - name: server_name
            value: "NPF FFA - Open Transport Tycoon Deluxe"
          - name: map_x
            value: "12"
          - name: map_y
            value: "12"
        resources:
          requests:
            memory: "5000Mi"
            cpu: "3"
        volumeMounts:
        - mountPath: /home/openttd/.openttd/
          name: openttd-config
      volumes:
      - name: openttd-config
        configMap:
          name: openttd
          items:
          - key: config
            path: openttd.cfg
---
kind: Service
apiVersion: v1
metadata:
  name: openttd
  labels:
    app: openttd
spec:
  selector:
    app: openttd
  ports:
    - name: openttd-tcp
      protocol: TCP
      port: 3979
      targetPort: 3979
    - name: openttd-udp
      protocol: UDP
      port: 3979
      targetPort: 3979
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openttd
  labels:
    name: openttd-config
data:
  config: |-
    map_x = 10
    map_y = 10
